CREATE TABLE IF NOT EXISTS entrances (
	id INTEGER PRIMARY KEY AUTOINCREMENT,
	agent TEXT NOT NULL,
	check_in DATETIME NOT NULL,
	check_out DATETIME NOT NULL,
	created_at DATETIME NOT NULL,
	updated_at DATETIME NOT NULL
);